name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say helloww
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          echo "dia"